POST http://localhost:3000/api/adoptantes/crear
Content-Type: application/json

{
    "nombre": "ENCRIPTADO",
    "apellidos": "ENCRIPTADO",
    "direccion": "DIRENCRIPTADO 4",
    "email": "encriptado@mail.com",
    "telefono": 898767545,
    "localidad": "ENCRIPTADO",
    "provincia": "Madrid",
    "tiene_gato": "no",
    "espacio_exterior": "si",
    "metros_exterior": 7,
    "tipo_vivienda": "casa/chalet",
    "tipo_espacio_exterior": "patio",
    "fotos_casa": "https://i.ytimg.com/vi/SsdNJTN_mZI/maxresdefault.jpg",
    "password": 654321
}

###

PUT http://localhost:3000/api/adoptantes/17
Content-Type: application/json

{
    "nombre": "UPDATE",
    "apellidos": "UPDATE",
    "direccion": "UPDATE 4",
    "email": "UPDATE@mail.com",
    "telefono": 898767545,
    "localidad": "UPDATE",
    "provincia": "Madrid",
    "tiene_gato": "no",
    "espacio_exterior": "si",
    "metros_exterior": 7,
    "tipo_vivienda": "casa/chalet",
    "tipo_espacio_exterior": "patio",
    "fotos_casa": "https://i.ytimg.com/vi/SsdNJTN_mZI/maxresdefault.jpg",
    "password": 654321
}

###

POST http://localhost:3000/api/adoptantes/login
Content-Type: application/json

{
    "password": "Cucu1",
    "email": "cucu@mail.com"
}

