GET http://localhost:3000/api/protectoras

###
POST http://localhost:3000/api/protectoras
Content-Type: application/json

{
    "nombre": "proteprueba5",
    "email": "proteprueba5",
    "telefono": 1777777,
    "direccion": "proteprueba5",
    "localidad": "proteprueba5",
    "provincia": "Madrid",
    "latitud": "proteprueba5",
    "longitud": "proteprueba5",
    "necesidad_voluntarios": "alta",
    "imagen": "proteprueba5",
    "comentarios": "proteprueba3proteprueba3proteprueba3proteprueba3proteprueba3proteprueba3",
    "password_protectora": "Prote5"

}

###
GET http://localhost:3000/api/protectoras/edita/12
Content-Type: application/json

{
    "comentarios": "leti prueba coment",
    "password_protectora": 12345
}


###
GET http://localhost:3000/api/protectoras/borrar/8


###
GET http://localhost:3000/api/protectoras/coordenadas/coordenadas

###
GET http://localhost:3000/api/protectoras/perfil
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm90ZWN0b3JhSWQiOjE5LCJjYWR1Y2lkYWQiOjE2MDgyMDU4NDQsImlhdCI6MTYwODIwNTI0NH0.cd2YtRv-zmaP0zFxlOaAjJYOwBU5lFDbFW1k8CeJaFQ

###
POST http://localhost:3000/api/protectoras/login
Content-Type: application/json

{
    "password": "Enc1",
    "email": "enc1@mail.com"
}

###
GET http://localhost:3000/api/protectoras/datatable
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm90ZWN0b3JhSWQiOjE0LCJjYWR1Y2lkYWQiOjE2MDgyODAyNjUsImlhdCI6MTYwODI3OTY2NX0.enzwa4_kuCGYg5QgyqpVHBI03EWzWlOUwA0BV0LRtec


###
GET http://localhost:3000/api/protectoras/BorrarRelacion/24
