POST http://localhost:3000/api/adoptantes/crear
Content-Type: application/json

{
    "nombre": "cambio",
    "apellidos": "cambio",
    "direccion": "DIRcambio 4",
    "email": "cambio@mail.com",
    "telefono": 898767545,
    "localidad": "cambio",
    "provincia": "Madrid",
    "tiene_gato": "no",
    "espacio_exterior": "si",
    "metros_exterior": 7,
    "tipo_vivienda": "casa/chalet",
    "tipo_espacio_exterior": "patio",
    "fotos_casa": "https://i.ytimg.com/vi/SsdNJTN_mZI/maxresdefault.jpg",
    "password": "654321",
    "rol":"adoptante"
}

###

PUT http://localhost:3000/api/adoptantes/23
Content-Type: application/json

{
    "nombre": "nuevousuario",
    "apellidos": "nuevousuario",
    "direccion": "nuevousuario 4",
    "email": "nuevousuario@mail.com",
    "telefono": 898767545,
    "localidad": "nuevousuario",
    "provincia": "Madrid",
    "tiene_gato": "no",
    "espacio_exterior": "si",
    "metros_exterior": 7,
    "tipo_vivienda": "casa/chalet",
    "tipo_espacio_exterior": "patio",
    "fotos_casa": "https://i.ytimg.com/vi/SsdNJTN_mZI/maxresdefault.jpg",
    "password": 654321
}

###

POST http://localhost:3000/api/adoptantes/login
Content-Type: application/json

{
    "password": "Nuevo1",
    "email": "nuevousuario@mail.com"
}

###

GET http://localhost:3000/api/perros
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG9wdGFudGVJZCI6MjMsImNhZHVjaWRhZCI6MTYwNzg3ODI3MywiaWF0IjoxNjA3ODc3NjczfQ.-XoI63--45XdXMvKhxS87PBrwC_5wza9F5kPrU4YPIw

###

GET http://localhost:3000/api/adoptantes/perfil
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG9wdGFudGVJZCI6MjMsImNhZHVjaWRhZCI6MTYwNzg3ODI3MywiaWF0IjoxNjA3ODc3NjczfQ.-XoI63--45XdXMvKhxS87PBrwC_5wza9F5kPrU4YPIw

###

GET  http://localhost:3000/api/adoptantes/3/perrosfavoritos
