GET http://localhost:3000/api/protectoras

###
POST http://localhost:3000/api/protectoras
Content-Type: application/json

{
    "nombre": "leti",
    "email": "leti",
    "telefono": 1,
    "direccion": "leti",
    "localidad": "leti",
    "provincia": "leti",
    "latitud": 1,
    "longitud": 1,
    "necesidad_voluntarios": "alta",
    "imagen": "leti",
    "comentarios": "leti",
    "password_protectora": 1234

}

###
GET http://localhost:3000/api/protectoras/edita/12
Content-Type: application/json

{
    "comentarios": "leti prueba coment",
    "password_protectora": 12345
}


###
GET http://localhost:3000/api/protectoras/borrar/8


###
GET http://localhost:3000/api/protectoras/coordenadas/coordenadas
